# Generated by Django 4.2.25 on 2025-10-30 09:06

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('communication_node', models.TextField(blank=True, max_length=60, null=True, verbose_name='Aloqa tugun')),
                ('m_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harbiy qism')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim')),
                ('rank', models.CharField(blank=True, max_length=40, null=True, verbose_name='Harbiy unvon')),
                ('date_brith', models.DateTimeField(blank=True, null=True, verbose_name='Tugilgan yil')),
                ('photo', models.ImageField(blank=True, default='profile_pics/user.png', null=True, upload_to='profile_pics', verbose_name='Xodim Rasmi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Umumiy ball')),
                ('point', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Foydalnuvchiga izoh')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='telefon bolimi nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='telefon egasi fio')),
                ('panasonic_number', models.CharField(max_length=5, verbose_name='panasonic ')),
                ('zas_number', models.CharField(max_length=5, verbose_name='zas')),
                ('grandstream_number', models.CharField(max_length=5, verbose_name='grandstream')),
                ('city_number', models.CharField(max_length=12, verbose_name='shahar telefon raqami')),
                ('mobile_number', models.CharField(max_length=12, verbose_name='mobile number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonedepartment', to='network.phonedepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Tadbir haqida qisqacha malumot')),
                ('m_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Harbiy qism')),
                ('communication_node', models.TextField(blank=True, max_length=60, null=True, verbose_name='Aloqa tugun')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tadbir_images/', verbose_name='Tadbir rasmi')),
                ('main_body', ckeditor.fields.RichTextField(verbose_name='Asosiy qism')),
                ('comment_theme', models.CharField(blank=True, max_length=300, null=True, verbose_name='tadbir mavzusi')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tadbirga izoh')),
                ('done', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Tadbir vaqti')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.region', verbose_name='Hudud nomi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Qurilma nomi')),
                ('type', models.CharField(blank=True, choices=[('BazaStansiya', 'BazaStansiya'), ('PATS', 'PATS'), ('GATS', 'GATS'), ('L3VLAN', 'L3VLAN')], max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True, verbose_name='IP Manzil')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='faollik')),
                ('last_checked', models.DateTimeField(auto_now=True, null=True, verbose_name='oxirgi ozgarishlar')),
                ('koorX', models.FloatField(blank=True, null=True, verbose_name='X koordinata')),
                ('koorY', models.FloatField(blank=True, null=True, verbose_name='Y koordinata')),
                ('jolashuvi', models.CharField(blank=True, max_length=60, null=True, verbose_name='qurilma jolashgan joyi')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qurilma model')),
                ('year', models.DateField(blank=True, null=True, verbose_name='yil')),
                ('full_info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='toliq malumot')),
                ('javob_shax', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='javobgar shaxslar va tel raqamlar')),
                ('ichki_nomer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ichki nomerlar')),
                ('comment_theme', models.CharField(blank=True, max_length=100, null=True, verbose_name='izoh mavzusi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='izoh')),
                ('off_times', models.IntegerField(default=0, verbose_name='off times')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.region', verbose_name='Hudud nomi')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.region', verbose_name='Hudud nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
