# Generated by Django 4.2.25 on 2025-10-30 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_b', models.DateField()),
                ('date_f', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties_region', to='network.region')),
                ('user_outlook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties_outlook', to=settings.AUTH_USER_MODEL)),
                ('user_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties_phone', to=settings.AUTH_USER_MODEL)),
                ('user_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties_radio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
