# Generated by Django 4.2.25 on 2025-10-30 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='m_unit',
            field=models.CharField(default=".", max_length=30, verbose_name='m_unit'),
            preserve_default=False,
        ),
    ]
