# Generated by Django 4.2.25 on 2025-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_duty_m_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, choices=[('BazaStansiya', 'BazaStansiya'), ('PATS', 'PATS'), ('GATS', 'GATS'), ('VLAN', 'VLAN'), ('Abonent', 'Abonent')], max_length=30, null=True),
        ),
    ]
