# Generated by Django 4.2.25 on 2025-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='m_unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Harbiy qism'),
        ),
    ]
