# Generated by Django 4.2.25 on 2025-10-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rating_total_score_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='total_score',
        ),
    ]
