# Generated by Django 4.2.25 on 2025-11-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_rating_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, choices=[('BazaStansiya', 'BazaStansiya'), ('Firewall', 'Firewall'), ('PATS', 'PATS'), ('GATS', 'GATS'), ('VLAN', 'VLAN'), ('Abonent', 'Abonent')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='MUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_view_units', models.ManyToManyField(blank=True, related_name='viewed_by', to='network.munit')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='m_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='m_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='m_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='m_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
    ]
