# Generated by Django 4.2.25 on 2025-11-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_device_type_munit_alter_device_m_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='m_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='m_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='m_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='m_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.munit'),
        ),
    ]
